### ISSUE TITLE
Calendar > Event Start Triggers not triggering for ical Calendar entries 

### ISSUE THREAD

**Issue by schale01** [tybritten/ical-sensor-homeassistant#96]
Seeing this error in the log and the new Trigger:
Calendar > Event Start does not trigger. 

Possibly related to the component still using the depreciated CalendarDeviceEntity.   
https://developers.home-assistant.io/blog/2022/04/18/calendar-data-model/

Logger: homeassistant.components.automation.work_meetings
Source: components/automation/__init__.py:591
Integration: Automation (documentation, issues)
First occurred: 7:56:30 AM (10 occurrences)
Last logged: 9:15:22 AM

Got error 'Entity does not exist calendar.ical_calendar or is not a calendar entity' when setting up triggers for Work Meetings

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/trigger.py:130
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 8:56:23 AM (13 occurrences)
Last logged: 9:25:05 AM

[140314739138816] Got error 'Entity does not exist calendar.ical_calendar or is not a calendar entity' when setting up triggers for
[140314682677952] Got error 'Entity does not exist calendar.ical_calendar or is not a calendar entity' when setting up triggers for
[140314742979792] Got error 'Entity does not exist calendar.ical_calendar or is not a calendar entity' when setting up triggers for

**Comment by PeterCicaMolnar** [comment]
Same error here :(
It would be great if I can use iCal compontent as a trigger! 👍

**Comment by Anwen747** [comment]
Just discovered this component today, it is perfect for what I want to do, but I am having the same problems.  Seeing a warning in the log:

`CalendarEventDevice is deprecated, modify ICalCalendarEventDevice to extend CalendarEntity`

and the same error as the others when trying to use an automation trigger:

`Got error 'Entity does not exist calendar.ical_trash_and_recycle or is not a calendar entity' when setting up triggers for Turn on trash boolean`

I would really love to be able to use this integration fully.  Thanks!

**Comment by andreheuer** [comment]
I would also like to use this integration, however, I do receive the same error making the integration almost useless :-(

**Comment by Ottomaane** [comment]
same here.

**Comment by tiaanv** [comment]
For a temporary workaround, until codeowners can get round to a update see #91

**Comment by tybritten** [comment]
fixed in https://github.com/tybritten/ical-sensor-homeassistant/pull/97 1.6.0

**Comment by jmgiaever** [comment]
Hi,
I'm on 1.6.0 and still get the error:
```
Got error 'Entity does not exist calendar.trash_collection or is not a calendar entity' when setting up triggers for Trash collection: Glass and metal
```

Here's the config:
```
calendar:
  - platform: entities_calendar
    calendars:
      - name: Trash collection
        entities:
          - entity: sensor.remiks_glass_og_metallemballasje_kirkegardsvegen_14
            name: "Glass and metal"
            start_time:
              timestamp_attribute: start_time
            all_day: true

automation:
  - id: "trash_collection_glass_metal"
    alias: "Trash collection: Glass and metal"
    trigger:
      platform: calendar
      event: start
      entity_id: calendar.trash_collection
      offset: "-06:00:00"
    action:
      - service: system_log.write
        data:
          level: warning
          message: "{{ trigger }}"
```

![image](https://user-images.githubusercontent.com/7188121/187076016-da1b36d7-7d3b-478a-b8c2-9f404e7669f6.png)
